# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
group :development do

  # Sass, Compass and extensions.
  gem 'sass', '~> 3.3.9'                    # Sass.
  gem 'sassy-maps','< 1.0.0'
  gem 'sass-globbing'           # Import Sass files based on globbing pattern.
  gem 'compass', '~> 1.0.0.alpha.20'                # Framework built on Sass.
  gem 'compass-validator'       # So you can `compass validate`.
  gem 'compass-normalize'       # Compass version of normalize.css.
  gem 'compass-rgbapng'         # Turns rgba() into .png's for backwards compatibility.
  gem 'susy', '~> 2.1.2'                    # Susy grid framework.
#  gem 'singularitygs'           # Alternative to the Susy grid framework.
  gem 'toolkit'                 # Compass utility from the fabulous Snugug.
  gem 'breakpoint'              # Manages CSS media queries.
  gem 'oily_png'                # Faster Compass sprite generation.
  gem 'css_parser'              # Helps `compass stats` output statistics.
  gem 'compass-core'
  gem 'rb-fsevent'
  gem 'rb-inotify'
  gem 'ffi'
  gem 'chunky_png'
  gem 'compass-recipes'
  gem 'bootstrap-sass'

  gem "rack-livereload", :group => :development

  # Guard
  gem 'guard'
  gem 'guard-livereload', require: false
  gem 'guard-compass'
  gem 'guard-shell'
  gem 'yajl-ruby'               # Faster JSON with LiveReload in the browser.

  # Dependency to prevent polling. Setup for multiple OS environments.
  # Optionally remove the lines not specific to your OS.
  # https://github.com/guard/guard#efficient-filesystem-handling
  # gem 'rb-inotify', '~> 0.9', :require => false      # Linux
  # gem 'rb-fsevent', :require => false                # Mac OSX
  # gem 'rb-fchange', :require => false                # Windows

end
